Rewrites for the new Fundamentals section of docs
umbraco/OurUmbraco pull request #693
Opened 2021-04-23 12:07 UTC by sofietoft

**This PR is dependant on a Docs PR: https://github.com/umbraco/UmbracoDocs/pull/3092.
Do not merge this before the Docs PR has been merged.**

We're in the process of implementing a new Getting Started section in the Documentation.

The current "Getting Started" section will be renamed Fundamentals.
The rewrites added in this PR should make sure that everything from the old Getting Started section is redirected over to the Fundamentals section.
There is a rewrite rule for each if the sub-sections in the Getting Started section, and they are redirected to their new path in the Fundamentals section.

2021-04-27 12:13 UTC, dampee commented on OurUmbraco.Site/web.vsts.config
> +		<!-- START - Renaming Getting Started to Fundamentals -->
I would not use the "START" and "END" comments as someone might add a new line in between, otherwise, I can not see a mistake

2021-05-20 08:41 UTC, sigrundis requested changes
Looks good except for one leftover mistake from copy-paste. Change the name of the code URL redirect from Design to **Code**. 

After that is fixed you can merge 👏

2021-05-20 08:41 UTC, sigrundis commented on OurUmbraco.Site/web.vsts.config
> +		<rule name="Design" patternSyntax="Wildcard">
This needs to be changed to:
`<rule name="Code" patternSyntax="Wildcard">`

After that is fixed, everything looks perfect ✨

2021-05-20 08:50 UTC, sigrundis approved these changes

2021-05-26 07:01 UTC, merged